baseURL = 'https://vimwaer.vercel.app/'
languageCode = 'en-us'
title = 'Vimwaer'
description = 'Confessions of an English API Eater'
theme = 'archie'

[params]
    mode = "auto"
    subtitle = "Confessions of an English API Eater"
